# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - LiftBigMobile-API

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # - name: Run tests
      #   run: npm run test

      - name: Prepare deployment zip
        run: |
          rm -rf node_modules
          zip -r deploy.zip dist package.json package-lock.json
          ls -lh deploy.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_933799062E2A4DA1B4FC1A99B595D2D4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7C76A72633814510AA5A540FB1A4169C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FE6F12746D4940CEB5AAFD7D80E0391C }}

      - name: Configure app
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp config appsettings set --name LiftBigMobile-API \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --settings \
              SCM_DO_BUILD_DURING_DEPLOYMENT=true \
              NODE_ENV=production
            az webapp config set --name LiftBigMobile-API \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --startup-file "node dist/main.js"

      - name: Deploy zip
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LiftBigMobile-API'
          package: deploy.zip

      - name: Restart app
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp restart --name LiftBigMobile-API \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
